server:
  port: 5500
 
spring:
  application:
    name: bear-api

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: asia987ASDzkjciusad
    url: "jdbc:postgresql://dbfrancis.cklwjgefpvph.us-east-2.rds.amazonaws.com:5432/dbfrancis"
    username: csfrancis
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
    show-sql: false
    
