
spring:
  profiles:
    active: dev

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: esport_tracker
    show-sql: false
    
---
spring:
  profiles: dev    

server:
  port: 8092

